log

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,13 +20,12 @@ jobs:
     - uses: actions/checkout@v4
     - name: Run the e2e tests
       run: |
-        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend || exit_code=$?
+        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend
+        docker compose -f compose.yml -f compose.ci.yml up migration || exit_code=$
         if [ ! -z "$exit_code" ]; then
-          echo "Error starting migration-endtoend container. Fetching logs..."
+          echo "Error starting containers. Fetching logs..."
           docker compose -f compose.yml -f compose.ci.yml logs migration-endtoend
           exit $exit_code
         fi
-
-        docker compose -f compose.yml -f compose.ci.yml up migration
       env:
         RUBY_VERSION: ${{ matrix.ruby }}
