Output logs when failed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,10 +20,13 @@ jobs:
     - uses: actions/checkout@v4
     - name: Run the e2e tests
       run: |
-        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend
+        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend || exit_code=$?
+        if [ ! -z "$exit_code" ]; then
+          echo "Error starting migration-endtoend container. Fetching logs..."
+          docker compose -f compose.yml -f compose.ci.yml logs migration-endtoend
+          exit $exit_code
+        fi
+
         docker compose -f compose.yml -f compose.ci.yml up migration
       env:
         RUBY_VERSION: ${{ matrix.ruby }}
-    - name: Fetch migration-endtoend logs
-      run: |
-        docker compose -f compose.yml -f compose.ci.yml logs migration-endtoend
